require:
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/rake
    - bin/rspec
    - bin/rubocop
    - vendor/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

RSpec/NestedGroups:
  Max: 5

Layout/LineLength:
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 2

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false